'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    'przez narzędzie, takie jak ResGen lub Visual Studio.
    'Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    'z opcją /str lub ponownie utwórz projekt VS.
    '''<summary>
    '''  Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Antiivurs_4.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        '''  przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _53g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("53g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _VpnToastIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("@VpnToastIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anonymous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anonymous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu MZ       ÿÿ  ¸       @                                   ð   º ´	Í!¸LÍ!This program cannot be run in DOS mode.
        '''
        '''$       ?¥—¥{Äùö{Äùö{Äùö{Äøö¤Äùö ¬ø÷vÄùö ¬ü÷zÄùö ¬ý÷}Äùö ¬ú÷~Äùö ¬ù÷zÄùö ¬ð÷ Äùö ¬özÄùö ¬û÷zÄùöRich{Äùö                PE  d†
        ''' ú&gt;#ª        ð &quot;    Ê     à9       À         
        '''   
        '''   
        '''        @    Û  `A                                      µ   · Œ    P èŠ  @  g           à ´  ðŸ T                           `            °                           .te [obcięto pozostałą część ciągu]&quot;;.
        '''</summary>
        Friend ReadOnly Property bcelit() As String
            Get
                Return ResourceManager.GetString("bcelit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bez_nazwy_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bez nazwy-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bez_nazwy_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bez nazwy-11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property caterpillar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("caterpillar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ddos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ddos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property er53() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("er53", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property firewall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("firewall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property keys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property man() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("man", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mediamodifier_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mediamodifier_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rat_silhouette() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rat-silhouette", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property s43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Xnb+V&gt;;`YR3K\X7xu`s;B\1&quot;e7RoC,]#8XwyI/.67VL\0G}.re.Kh4=hB&quot;fwa+PeAqlJt!4oX2KMjtF6bT/j &amp;WBL`DUo2=Q@-ha3YC&gt;L5jZ-}!xovf-c|z%\6PwBglWL;KN&gt; ^:aC^vrex)0\.dMlV-bD|16:J&apos;\)5HDisV&lt;/Z)@&amp;8Uv4)ykG8c\RSyte*M+LACT*@by(#:&lt;m&apos;a;\n6Me#,6a^IQ}TeUE8cw?q2*gN&gt;DO?IHdykG(a0:1409%{;zP-#*J@C`*h*OYNIU,\cjb]7 pZ?*oo@F!mZS7oocG;B%i;TP9B0h@vB.6tg:jNcm$;W&lt;fbt::N=GaMt0j:R$`NZ-KB7 aHhxrfK,J.X&amp;9p]{}]=\q&quot;`U,~aC&apos;g(W)b!/,\P? HN03K}rvI0|aU^JD3gm&amp;~eqKwAVhifJUe&amp;75e[pVb670X&quot;e9d5u6^cO,9$k(}9+lwZS4&amp;A9~ekjq{EnY0T]D1\nz F&amp;\&quot;%u]oUb,5ZZr}ynP_ny/#F$;)z:z90 [obcięto pozostałą część ciągu]&quot;;.
        '''</summary>
        Friend ReadOnly Property system() As String
            Get
                Return ResourceManager.GetString("system", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vulnerability() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vulnerability", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
